import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | AnyForm',
  description: 'Terms of Service for AnyForm - The AI Form Builder',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-paper-texture pt-24 pb-16 font-paper text-black">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-bold text-black mb-4">Terms of Service</h1>
        <p className="text-black/60 mb-8 font-bold">Last updated: December 23, 2025</p>

        {/* Beta Notice */}
        <div className="bg-transparent border-2 border-dashed border-black/20 rounded-xl p-6 mb-10">
          <h3 className="text-black font-bold mb-2 text-lg">🚧 Beta Notice</h3>
          <p className="text-black/80 text-sm font-bold">
            AnyForm is currently in <strong>Beta</strong>. We are a bootstrapped startup, which means we move fast and push updates frequently. While we strive for stability, you may encounter bugs, downtime, or rapid changes to features. By using AnyForm, you acknowledge that you are using an early-access product.
          </p>
        </div>

        <div className="prose prose-neutral max-w-none text-black/80 font-paper">
          <p className="lead text-lg">
            Welcome to AnyForm! We're building the fastest way to create forms using AI. By using our service, you agree to these simple terms.
          </p>

          <h2 className="text-2xl font-bold text-black mt-8 mb-4">1. The Basics</h2>
          <p>
            AnyForm is provided "as is" and "as available". We make no warranties, expressed or implied, and hereby disclaim all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
          </p>

          <h2 className="text-2xl font-bold text-black mt-8 mb-4">2. Your Account & Content</h2>
          <p>
            You are responsible for keeping your account secure. Any content you generate or upload remains yours. However, by using the service, you give us permission to host, process, and display that content as needed to provide the service to you.
          </p>
          <ul className="list-disc pl-5 mt-4 space-y-2 marker:text-black/40">
            <li>You own your data.</li>
            <li>You are responsible for the content you post.</li>
            <li>Don't use AnyForm for anything illegal or malicious.</li>
          </ul>

          <h2 className="text-2xl font-bold text-black mt-8 mb-4">3. AI Limitations</h2>
          <p>
            Our service uses Artificial Intelligence to generate forms. AI can make mistakes (&quot;hallucinations&quot;). Please review all generated forms before sharing them. We are not responsible for inaccuracies in the content generated by the AI.
          </p>

          <h2 className="text-2xl font-bold text-black mt-8 mb-4">4. Liability</h2>
          <p>
            We're a small team doing our best, but we cannot be held liable for any damages arising from the use of our service. This includes, but is not limited to, loss of data, loss of profits, or business interruption.
          </p>

          <h2 className="text-2xl font-bold text-black mt-8 mb-4">5. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to AnyForm at any time, for any reason, without notice—though we'll generally only do this if you violate these terms or abuse the service.
          </p>

          <h2 className="text-2xl font-bold text-black mt-8 mb-4">6. Contact Us</h2>
          <p>
            Have questions, feedback, or found a bug? We'd love to hear from you.
            <br />
            Email us at <a href="mailto:support@anyform.live" className="text-black font-bold underline hover:text-black/70">support@anyform.live</a>.
          </p>
        </div>
      </div>
    </div>
  );
}


